function myfs_synthstrip(Fn)
if not(isfile(spm_file(Fn, 'suffix', '_n4')))
  mysystem(['mri_nu_correct.mni --ants-n4 ', ...
    ' --i ',Fn, ...
    ' --o ',spm_file(Fn,'suffix','_n4')]); % this conforms to UINT8
end
if not(isfile(spm_file(Fn, 'suffix', '_brain')))
  mysystem(['mri_synthstrip ', ...
    ' -i ',spm_file(Fn,'suffix','_n4'), ...
    ' -o ',spm_file(Fn,'suffix','_brain'), ...
    ' -m ',spm_file(Fn,'suffix','_mask')]);
end
end
